package execution

import (
	"crypto/rand"
	"encoding/hex"
	"time"

	"github.com/yargotev/exito-tools/internal/capability"
)

const requestIDBytes = 16

// Metadata contains per-command execution metadata shared by JSON envelopes.
type Metadata struct {
	RequestID     string
	CorrelationID string
	Duration      time.Duration
}

// NewRequestID returns an opaque request identifier generated by Exito Tools.
func NewRequestID() (string, error) {
	bytes := make([]byte, requestIDBytes)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}

	return "req_" + hex.EncodeToString(bytes), nil
}

// NewMetadata converts command timing and correlation inputs into shared metadata.
func NewMetadata(requestID string, correlationID string, startedAt time.Time, finishedAt time.Time) Metadata {
	duration := finishedAt.Sub(startedAt)
	if duration < 0 {
		duration = 0
	}

	return Metadata{
		RequestID:     requestID,
		CorrelationID: correlationID,
		Duration:      duration,
	}
}

// EnvelopeMeta returns the standard Envelope metadata shape for a command result.
func (m Metadata) EnvelopeMeta(profile string, capabilityID string) capability.EnvelopeMeta {
	return capability.EnvelopeMeta{
		RequestID:     m.RequestID,
		CorrelationID: m.CorrelationID,
		Profile:       profile,
		CapabilityID:  capabilityID,
		DurationMS:    m.Duration.Milliseconds(),
	}
}
